#!/usr/bin/env bash
# Create pipeline storage dirs under FASTQ_PIPELINE_ROOT and write config/paths.config
# and config/install_paths.env (sourceable; adds conda, uv, nextflow to PATH).
# Usage: export FASTQ_PIPELINE_ROOT=/path/to/storage && ./scripts/setup_dirs.sh
# Or:    FASTQ_PIPELINE_ROOT=/path ./scripts/setup_dirs.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$PROJECT_DIR/config"

ROOT="${FASTQ_PIPELINE_ROOT:-$PROJECT_DIR/storage}"
if [[ -z "${FASTQ_PIPELINE_ROOT:-}" ]]; then
  echo "FASTQ_PIPELINE_ROOT is not set. Using default: $ROOT"
fi
mkdir -p "$ROOT"
# Resolve to absolute path
if command -v realpath &>/dev/null; then
  ROOT="$(realpath "$ROOT")"
else
  ROOT="$(cd "$ROOT" && pwd)"
fi

echo "Creating directories under: $ROOT"
mkdir -p "$ROOT/large_files/merged_fastq"
mkdir -p "$ROOT/large_files/fastqc"
mkdir -p "$ROOT/work"
mkdir -p "$ROOT/conda_env"
mkdir -p "$ROOT/miniconda_env"
mkdir -p "$ROOT/conda_packages"
mkdir -p "$ROOT/miniconda_packages"
mkdir -p "$ROOT/tmp"
mkdir -p "$CONFIG_DIR"

# ---- paths.config for Nextflow ----
PATHS_CONFIG="$CONFIG_DIR/paths.config"
cat > "$PATHS_CONFIG" << EOF
// Generated by scripts/setup_dirs.sh - do not edit by hand
params {
    storage_root = "$ROOT"
    work_dir = "$ROOT/work"
    large_files_dir = "$ROOT/large_files"
    merged_fastq_dir = "$ROOT/large_files/merged_fastq"
    publish_fastqc_dir = "$ROOT/large_files/fastqc"
    conda_cache_dir = "$ROOT/conda_env"
    conda_packages_dir = "$ROOT/conda_packages"
    tmp_dir = "$ROOT/tmp"
}
workDir = params.work_dir
conda.cacheDir = params.conda_cache_dir
EOF
echo "Wrote $PATHS_CONFIG"

# ---- Discover and write install_paths.env ----
CONDA_ROOT="${CONDA_ROOT:-}"
if [[ -z "$CONDA_ROOT" ]] && command -v conda &>/dev/null; then
  CONDA_ROOT="$(conda info --base 2>/dev/null || true)"
fi
if [[ -z "$CONDA_ROOT" ]] && command -v conda &>/dev/null; then
  _conda_bin="$(command -v conda)"
  CONDA_ROOT="$(dirname "$(dirname "$_conda_bin")")"
fi

MINICONDA_ROOT="${MINICONDA_ROOT:-$CONDA_ROOT}"

UV_BIN=""
if [[ -n "${UV_HOME:-}" ]]; then
  UV_BIN="$UV_HOME"
elif [[ -n "${UV_BIN:-}" ]]; then
  :
elif command -v uv &>/dev/null; then
  _uv="$(command -v uv)"
  UV_BIN="$(dirname "$_uv")"
  UV_BIN="$(cd "$UV_BIN" && pwd)"
fi

NEXTFLOW_BIN=""
if [[ -n "${NEXTFLOW_BIN:-}" ]]; then
  :
elif command -v nextflow &>/dev/null; then
  _nf="$(command -v nextflow)"
  NEXTFLOW_BIN="$(dirname "$_nf")"
  NEXTFLOW_BIN="$(cd "$NEXTFLOW_BIN" && pwd)"
fi

INSTALL_ENV="$CONFIG_DIR/install_paths.env"
{
  echo "# Generated by scripts/setup_dirs.sh - source this to get conda, uv, nextflow on PATH"
  echo "# Usage: source $INSTALL_ENV"
  echo ""
  if [[ -n "$CONDA_ROOT" ]]; then
    echo "export CONDA_ROOT=\"$CONDA_ROOT\""
    echo "export MINICONDA_ROOT=\"$MINICONDA_ROOT\""
    echo 'export PATH="${CONDA_ROOT}/bin:${PATH}"'
  else
    echo "# CONDA_ROOT not found (set CONDA_ROOT or ensure conda is on PATH and re-run)"
  fi
  if [[ -n "$UV_BIN" ]]; then
    echo "export UV_BIN=\"$UV_BIN\""
    echo 'export PATH="${UV_BIN}:${PATH}"'
  else
    echo "# UV_BIN not found (set UV_BIN or install uv and re-run)"
  fi
  if [[ -n "$NEXTFLOW_BIN" ]]; then
    echo "export NEXTFLOW_BIN=\"$NEXTFLOW_BIN\""
    echo 'export PATH="${NEXTFLOW_BIN}:${PATH}"'
  else
    echo "# NEXTFLOW_BIN not found (set NEXTFLOW_BIN or install nextflow and re-run)"
  fi
} > "$INSTALL_ENV"
echo "Wrote $INSTALL_ENV"
echo "Source it so executables are on PATH: source $INSTALL_ENV"
